"""SOS-09-F emitted vectors — family=atomicity.

Auto-generated by ``tools/sos-codegen/vectors_emit.py`` per
``docs/concepts/SOS-09-F-CONCEPTS.md`` (ratified 2026-05-26).

Chart-id: sis08_first_slice
Vectors:  4
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from vectors.base import ChannelVectorPlan, VectorFamily
from vectors.families.atomicity import vector_class
from vectors.harness import PythonCpuStubHarness


_PLANS_JSON = Path(__file__).parent / "plans.json"


def _load_plans():
    raw = json.loads(_PLANS_JSON.read_text(encoding="utf-8"))
    plans = []
    for p in raw["plans"]:
        if "atomicity" not in p["families"]:
            continue
        plan = ChannelVectorPlan(
            channel_id=p["channel_id"],
            channel_name=p["channel_name"],
            channel_kind=p["channel_kind"],
            channel_zone=p["channel_zone"],
            channel_dir=p["channel_dir"],
            address=p["address"],
            width_bits=p["width_bits"],
            irq=p.get("irq"),
            mutex=p.get("mutex"),
            privilege_region=p.get("privilege_region"),
        )
        plans.append(plan)
    return plans


@pytest.mark.parametrize("plan", _load_plans(), ids=lambda p: p.channel_name)
def test_atomicity(plan):
    """Exercise the atomicity vector for each annotated channel."""
    harness = PythonCpuStubHarness()
    harness.register_channel(
        address=plan.address,
        width_bits=plan.width_bits,
    )
    vec = vector_class(plan=plan, seq=0)
    vec.setup(harness)
    vec.stimulate(harness)
    vec.observe(harness)
    vec.assert_invariants(harness)
