"""SOS-09-F emitted cocotb conftest — pytest-XUnit collector.

Auto-generated by ``tools/sos-codegen/vectors_emit.py`` per
``docs/concepts/SOS-09-F-CONCEPTS.md`` §5.5 (ratified 2026-05-26).
"""

from __future__ import annotations

import sys
from pathlib import Path

# Make the SOS codegen tools importable.
_SOS_ROOT = Path(__file__).resolve().parents[4]
_TOOLS = _SOS_ROOT / "tools" / "sos-codegen"
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))
