"""SIS-08D C2-A bespoke membrane-contract integration vector.

Hand-authored (not regenerated by ``tools/sos-codegen/vectors_emit.py``)
to satisfy ``docs/todo/streamz/statechart-orchestration/TODO-SIS-08D-C2-IMPLEMENTATION-PLAN.md``
§5 step 1 (interpreted-simulation evidence) and §4 (membrane-contract
requirements).

This vector exercises the **agreement** between the software side
and the SOS membrane descriptor on:

  * **Layout** — every channel's address derived from
    ``plans.json`` matches the SOS-09-B SVD address-offset policy.
  * **Ownership** — the SRAM window is SOS-owned (declared via the
    chart's ``sos:kind="shared"`` + ``sos:mutex="sram_window_lock"``
    annotations); the software side reads / writes through the bus
    facade only.
  * **Lifecycle** — command-write → status-publish round-trip on
    the SRAM-window membrane: software issues ``Start``, the
    hardware publishes ``Busy`` then ``Ready``, software reads the
    status, software issues ``Stop`` to return to ``Idle``.
  * **Transfer surface** — single-slot mailbox discipline: a single
    in-flight transfer posts to the data channel, the notify
    channel's ``non_empty`` strobes high, the software drains and
    the ``non_empty`` clears on read.
  * **Failure mode** — command-write while busy returns an
    ``Error`` status code (state=0x03) with a non-zero
    ``error_code`` byte; reading the status latch clears the
    error_code per the chart's ``side_effect="clear-on-read"``
    annotation.

The encoding constants here MUST stay in sync with the chart's
``sis08d_c2_membrane.scxml`` header comment (``Command encoding``
and ``Status encoding`` blocks). Drift between the two is the
exact failure mode this vector is meant to surface.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from vectors.harness import PythonCpuStubHarness

# ---------------------------------------------------------------------------
# Encoding constants — MUST mirror the SCXML chart header comment.
# ---------------------------------------------------------------------------

# Command field offsets (membrane_command, see chart bit_layout).
CMD_FIELD_LSB = 0
CMD_FIELD_MASK = 0xFF
SEQ_FIELD_LSB = 8
SEQ_FIELD_MASK = 0xFF00

# Status field offsets (membrane_status, see chart bit_layout).
STATE_FIELD_LSB = 0
STATE_FIELD_MASK = 0xFF
ERROR_CODE_LSB = 16
ERROR_CODE_MASK = 0x00FF0000
BUSY_BIT = 1 << 31

# Notify field offsets (transfer_mailbox_notify).
NOTIFY_NON_EMPTY_BIT = 1 << 0
NOTIFY_PRIORITY_LSB = 8
NOTIFY_PRIORITY_MASK = 0x0F00

# Command opcodes.
CMD_IDLE = 0x00
CMD_START = 0x01
CMD_STOP = 0x02
CMD_DRAIN = 0x03

# Status state codes.
STATE_IDLE = 0x00
STATE_BUSY = 0x01
STATE_READY = 0x02
STATE_ERROR = 0x03

# Error codes (synthetic — the spec just demands non-zero on busy-write).
ERR_BUSY_WRITE_REJECTED = 0x42


# ---------------------------------------------------------------------------
# Layout helpers — load plans.json (the SOS-09-B address-offset evidence).
# ---------------------------------------------------------------------------

_PLANS_JSON = Path(__file__).parent / "plans.json"


def _load_layout() -> dict[str, dict]:
    """Return ``{channel_name: plan}`` mapping from the emitted plans.json."""
    raw = json.loads(_PLANS_JSON.read_text(encoding="utf-8"))
    return {p["channel_name"]: p for p in raw["plans"]}


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def test_c2a_layout_matches_sos09b_address_policy():
    """Layout invariant: SOS-09-B address-offset policy lays each 32-bit
    channel at a 4-byte cursor starting from the SVD baseAddress.

    The chart has five 32-bit channels; cursor must advance 4, 4, 4, 4.
    """
    layout = _load_layout()
    names = [
        "membrane_command",
        "membrane_status",
        "transfer_mailbox_data",
        "transfer_mailbox_notify",
        "sram_window",
    ]
    assert set(layout.keys()) == set(names), (
        f"chart channel set drifted from C2-A contract: {sorted(layout.keys())}"
    )
    base = layout["membrane_command"]["address"]
    for i, name in enumerate(names):
        expected = base + 4 * i
        actual = layout[name]["address"]
        assert actual == expected, (
            f"layout drift on {name!r}: SOS-09-B policy expects "
            f"0x{expected:08X}, plans.json says 0x{actual:08X}"
        )


def test_c2a_ownership_sram_window_is_shared_mutex_locked():
    """Ownership invariant: SRAM window is SOS-owned (kind=shared) and
    serialised under a named mutex. The membrane contract requires the
    software side to NOT embed the SOS descriptor into the graph node.
    """
    layout = _load_layout()
    sram = layout["sram_window"]
    assert sram["channel_kind"] == "shared", (
        f"sram_window must be kind=shared (SOS-owned region); got "
        f"{sram['channel_kind']!r}"
    )
    assert sram["mutex"] == "sram_window_lock", (
        "sram_window must be guarded by sram_window_lock per chart "
        "annotation; mutex value drifted"
    )
    # Mailbox data carries the queue discipline, not shared semantics.
    assert layout["transfer_mailbox_data"]["channel_kind"] == "queue", (
        "transfer_mailbox_data must be kind=queue per SIS-08D §4"
    )


def test_c2a_command_status_round_trip_lifecycle():
    """Lifecycle invariant: command-write → status-publish round trip.

    Software issues Start; the membrane publishes Busy, then Ready;
    software reads the status, issues Stop, returns to Idle.

    The Python CPU stub emulates the membrane by having the test
    drive both sides — that's faithful to SIS-08D §5 step 1
    (interpreted simulation, no compiled backend required).
    """
    layout = _load_layout()
    cmd_addr = layout["membrane_command"]["address"]
    status_addr = layout["membrane_status"]["address"]

    h = PythonCpuStubHarness()
    h.register_channel(address=cmd_addr, width_bits=32)
    # Status: clear-on-read on the error_code byte per chart annotation.
    h.register_channel(
        address=status_addr,
        width_bits=32,
        clear_on_read_mask=ERROR_CODE_MASK,
        initial_value=(STATE_IDLE << STATE_FIELD_LSB),
    )

    # Software-side: write Start with seq=1.
    cmd_word = (CMD_START << CMD_FIELD_LSB) | (1 << SEQ_FIELD_LSB)
    h.bus.write(cmd_addr, cmd_word)

    # Membrane (hardware-side stub): publish Busy.
    h._registers[status_addr].value = (STATE_BUSY << STATE_FIELD_LSB) | BUSY_BIT
    observed = h.bus.read(status_addr)
    assert (observed & STATE_FIELD_MASK) == STATE_BUSY, (
        f"expected Busy state after Start; got 0x{observed:08X}"
    )
    assert observed & BUSY_BIT, "busy bit must be set while in Busy state"

    # Membrane: publish Ready.
    h._registers[status_addr].value = STATE_READY << STATE_FIELD_LSB
    observed = h.bus.read(status_addr)
    assert (observed & STATE_FIELD_MASK) == STATE_READY, (
        f"expected Ready state after work; got 0x{observed:08X}"
    )

    # Software: issue Stop.
    h.bus.write(cmd_addr, (CMD_STOP << CMD_FIELD_LSB) | (2 << SEQ_FIELD_LSB))
    h._registers[status_addr].value = STATE_IDLE << STATE_FIELD_LSB
    observed = h.bus.read(status_addr)
    assert (observed & STATE_FIELD_MASK) == STATE_IDLE, (
        f"expected return to Idle after Stop; got 0x{observed:08X}"
    )


def test_c2a_mailbox_single_slot_post_drain_cycle():
    """Transfer-surface invariant: single-slot mailbox post / drain
    with notify-side clear-on-read on non_empty.

    Per SIS-08D §4 + SIS-03 §4.10, the v1 transfer surface is a
    mailbox (one in-flight transfer at a time). The notify channel's
    non_empty bit strobes high on post and clears on the software
    side's read of the notify register.
    """
    layout = _load_layout()
    data_addr = layout["transfer_mailbox_data"]["address"]
    notify_addr = layout["transfer_mailbox_notify"]["address"]

    h = PythonCpuStubHarness()
    h.register_channel(address=data_addr, width_bits=32)
    h.register_channel(
        address=notify_addr,
        width_bits=32,
        clear_on_read_mask=NOTIFY_NON_EMPTY_BIT,
    )

    # Mailbox is initially empty.
    assert h.bus.read(notify_addr) & NOTIFY_NON_EMPTY_BIT == 0, (
        "notify.non_empty should reset clear"
    )

    # Hardware-side post: a transfer descriptor lands in the data
    # surface, the notify register reflects it (non_empty=1, priority=5).
    PAYLOAD = 0xDEADBEEF
    h._registers[data_addr].value = PAYLOAD
    h._registers[notify_addr].value = NOTIFY_NON_EMPTY_BIT | (5 << NOTIFY_PRIORITY_LSB)

    # Software-side observes the notification.
    notify_word = h.bus.read(notify_addr)
    assert notify_word & NOTIFY_NON_EMPTY_BIT, "non_empty must be set on post"
    assert (notify_word & NOTIFY_PRIORITY_MASK) >> NOTIFY_PRIORITY_LSB == 5, (
        "priority byte must round-trip across the notify surface"
    )

    # Read clears the non_empty latch (chart annotation: clear-on-read).
    next_word = h.bus.read(notify_addr)
    assert next_word & NOTIFY_NON_EMPTY_BIT == 0, (
        "non_empty must clear on read per chart side_effect annotation"
    )

    # Software-side drain: read the data surface.
    drained = h.bus.read(data_addr)
    assert drained == PAYLOAD, (
        f"mailbox drain must return the posted payload; got 0x{drained:08X}"
    )

    # Single-slot discipline: posting a second transfer while the slot
    # is still nominally "drained but not re-armed" is permitted — the
    # contract is one in-flight at the notify-level, not one ever-posted.
    # This test exercises the round-trip; multi-slot discipline is
    # out of scope per SIS-08D §4 ("Use a single-slot mailbox … for v1").


def test_c2a_command_while_busy_returns_error_status():
    """Failure-mode invariant: command-write while busy publishes
    state=Error with a non-zero error_code. The error_code latch
    clears on read per the chart's clear-on-read annotation.
    """
    layout = _load_layout()
    cmd_addr = layout["membrane_command"]["address"]
    status_addr = layout["membrane_status"]["address"]

    h = PythonCpuStubHarness()
    h.register_channel(address=cmd_addr, width_bits=32)
    h.register_channel(
        address=status_addr,
        width_bits=32,
        clear_on_read_mask=ERROR_CODE_MASK,
        # Start in Busy state — the hardware-side stub publishes Busy.
        initial_value=(STATE_BUSY << STATE_FIELD_LSB) | BUSY_BIT,
    )

    # Software-side: try to issue a fresh Start while the membrane is busy.
    h.bus.write(cmd_addr, (CMD_START << CMD_FIELD_LSB) | (3 << SEQ_FIELD_LSB))

    # Membrane reaction: latch Error state with ERR_BUSY_WRITE_REJECTED.
    h._registers[status_addr].value = (
        (STATE_ERROR << STATE_FIELD_LSB)
        | (ERR_BUSY_WRITE_REJECTED << ERROR_CODE_LSB)
    )

    observed = h.bus.read(status_addr)
    assert (observed & STATE_FIELD_MASK) == STATE_ERROR, (
        f"expected Error state after busy-write; got 0x{observed:08X}"
    )
    assert (
        (observed & ERROR_CODE_MASK) >> ERROR_CODE_LSB
    ) == ERR_BUSY_WRITE_REJECTED, (
        "error_code byte must carry the rejected-while-busy code"
    )

    # Clear-on-read: a follow-up read must show error_code=0.
    follow_up = h.bus.read(status_addr)
    assert (follow_up & ERROR_CODE_MASK) == 0, (
        "error_code must clear on read per chart side_effect annotation; "
        f"got 0x{follow_up:08X}"
    )


# ---------------------------------------------------------------------------
# Layout-vs-MPU cross-check — informative; binds the SOS-09-G output to
# the SOS-09-B layout. Either artifact drifting from the chart trips the
# emitted-vector pipeline, so this test does not re-implement the
# emitter — it asserts the descriptor manifest exists and matches.
# ---------------------------------------------------------------------------


def test_c2a_manifest_references_all_emitted_artifacts():
    """The deterministic manifest must reference the chart, the SVD,
    both MPU tables (C + Rust), and every vector file under the
    chart's vector directory. Mismatch is a regression in the
    emitter, not the chart.
    """
    repo_root = Path(__file__).resolve().parents[4]
    manifest_path = (
        repo_root
        / "charts"
        / "sis08d_c2_membrane"
        / "sis08d_c2_membrane_manifest.json"
    )
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    assert manifest["id"] == "sis08d-c2-membrane"
    # Path B per EOQ-002-ERRATA-002 (2026-05-28): placement amended from
    # "sram-membrane" to "mmio-peripheral" because the C2-A target
    # access mechanism is memory-mapped IO, not memory-backed SRAM.
    # The chart's semantic surface (shared region with command/status/
    # transfer channels) is unchanged; only the access-mechanism tag is.
    assert manifest["placement"] == "mmio-peripheral"
    assert manifest["descriptor"]["format"] == "cmsis-svd-1.3"
    assert manifest["descriptor"]["contentHash"].startswith("sha256:")
    assert manifest["chartHash"].startswith("sha256:")
    assert manifest["mpu"]["c"].endswith("sis08d_c2_membrane_mpu.c")
    assert manifest["mpu"]["rust"].endswith("sis08d_c2_membrane_mpu.rs")
    # Five channels per SIS-08D §4.
    assert len(manifest["channels"]) == 5
    names = {c["name"] for c in manifest["channels"]}
    assert names == {
        "membrane_command",
        "membrane_status",
        "transfer_mailbox_data",
        "transfer_mailbox_notify",
        "sram_window",
    }
