// SPDX-License-Identifier: MIT
// SOS-08-F wave-1 emitted artifact — DO NOT EDIT BY HAND.
//
// Generated by ``tools/sos-codegen/transliterate_hdl_uvm_seq.py``.
//
// Spec references (per SOS-08-F §12 (h)+(i) acceptance gates):
//   * SOS-08-F-CONCEPTS.md §5..§7  (emission contract + invariants)
//   * SOS-07-CONCEPTS.md   §6      (INV-SOS-A..H cross-phase
//                                    invariants)
//   * SOS-07-CONCEPTS.md   §7      (AuthorityRelationship matrix —
//                                    UVM is `derive`)
//   * SOS-08-CONCEPTS.md   §7      (INV-S-HDL-1..5 cross-sub-phase
//                                    invariants; INV-S-HDL-5 = chart-
//                                    vocabulary traceability —
//                                    load-bearing on sos_seq_item
//                                    metadata fields below)
//
// Invariants upheld by this artifact:
//   * INV-S-HDL-F-1: sequences only (no env / agent / sequencer /
//                     driver / monitor / scoreboard / test /
//                     config_db emission).
//   * INV-S-HDL-F-2: customer owns env, scoreboard, driver, factory.
//   * INV-S-HDL-F-3: every sos_seq_item carries chart_state /
//                     transition_id / invariant_id chart-vocabulary
//                     metadata.
//   * INV-S-HDL-F-4: no SVA emission (no `assert property`, no
//                     `bind`); SVA is sibling SOS-08-D + SOS-08-E.
//   * INV-S-HDL-F-5: UVM 1.2 grammar only; runs unchanged on UVM 2.0.
//
//
// Header file: sos_uvm_seq_pkg.svh
//
// Provides typedef + enum exports for customers whose driver
// implementation needs the discriminated-union types without
// importing the full sequence library (e.g. drivers compiled
// separately from sequences). Most customers import the package
// directly; this header exists for split-compilation environments.
//
// Chart: rtos_kernel
//
`ifndef SOS_UVM_SEQ_PKG_SVH
`define SOS_UVM_SEQ_PKG_SVH

  // Discriminated-union family tag per §5.3 + §6.2.
  typedef enum {
    SOS_FAMILY_TASK,
    SOS_FAMILY_SEM,
    SOS_FAMILY_QUEUE,
    SOS_FAMILY_TIMER,
    SOS_FAMILY_EVENT,
    SOS_FAMILY_TICK
  } sos_event_family_e;

  // Vector-IR row shape consumed by per-family sequences per §6.4.
  typedef struct {
    int        event_id;
    bit [63:0] payload_data;
    string     chart_state;
    int        transition_id;
    int        invariant_id;
  } sos_chart_event_s;

`endif // SOS_UVM_SEQ_PKG_SVH
