// SPDX-License-Identifier: MIT
// SOS-08-F wave-1 emitted artifact — DO NOT EDIT BY HAND.
//
// Generated by ``tools/sos-codegen/transliterate_hdl_uvm_seq.py``.
//
// Spec references (per SOS-08-F §12 (h)+(i) acceptance gates):
//   * SOS-08-F-CONCEPTS.md §5..§7  (emission contract + invariants)
//   * SOS-07-CONCEPTS.md   §6      (INV-SOS-A..H cross-phase
//                                    invariants)
//   * SOS-07-CONCEPTS.md   §7      (AuthorityRelationship matrix —
//                                    UVM is `derive`)
//   * SOS-08-CONCEPTS.md   §7      (INV-S-HDL-1..5 cross-sub-phase
//                                    invariants; INV-S-HDL-5 = chart-
//                                    vocabulary traceability —
//                                    load-bearing on sos_seq_item
//                                    metadata fields below)
//
// Invariants upheld by this artifact:
//   * INV-S-HDL-F-1: sequences only (no env / agent / sequencer /
//                     driver / monitor / scoreboard / test /
//                     config_db emission).
//   * INV-S-HDL-F-2: customer owns env, scoreboard, driver, factory.
//   * INV-S-HDL-F-3: every sos_seq_item carries chart_state /
//                     transition_id / invariant_id chart-vocabulary
//                     metadata.
//   * INV-S-HDL-F-4: no SVA emission (no `assert property`, no
//                     `bind`); SVA is sibling SOS-08-D + SOS-08-E.
//   * INV-S-HDL-F-5: UVM 1.2 grammar only; runs unchanged on UVM 2.0.
//
//
// SystemVerilog package: sos_uvm_seq_pkg
//
// Per SOS-08-F §5.7 + PCDN-SOS-08-F-006: one consolidated package
// containing every per-family sequence subclass + the baseline
// transaction class. Customer imports with a single line:
//
//     import sos_uvm_seq_pkg::*;
//
// Per §5.5 + PCDN-SOS-08-F-004 the `uvm_object_utils` factory
// registrations live inside the package; customer does NOT need to
// register SOS classes manually. Customer MAY override via standard
// UVM `set_type_override_by_type` mechanics.
//
// Chart that authored this package: rtos_kernel
//
package sos_uvm_seq_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"

  // -------------------------------------------------------------------------
  // sos_event_family_e — discriminated-union tag per §5.3 + §6.2
  // -------------------------------------------------------------------------
  typedef enum {
    SOS_FAMILY_TASK,
    SOS_FAMILY_SEM,
    SOS_FAMILY_QUEUE,
    SOS_FAMILY_TIMER,
    SOS_FAMILY_EVENT,
    SOS_FAMILY_TICK
  } sos_event_family_e;

  // -------------------------------------------------------------------------
  // sos_chart_event_s — vector-IR row shape (consumed by sequence body())
  // -------------------------------------------------------------------------
  //
  // Per SOS-08-F §6.4 the per-family sequence's body() iterates a queue
  // of `sos_chart_event_s` rows loaded from the chart's bounded-
  // reachability JSONL. The fields below mirror the JSONL keys 1:1.
  typedef struct {
    int    event_id;       // chart-vocabulary event index within family
    bit [63:0] payload_data;
    string chart_state;    // chart-state name where this event originates
    int    transition_id;  // chart transition that produced this event
    int    invariant_id;   // optional chart invariant tag (0 if unused)
  } sos_chart_event_s;

  // -------------------------------------------------------------------------
  // sos_seq_item — baseline UVM transaction class (per §6.2)
  // -------------------------------------------------------------------------
  //
  // INV-S-HDL-F-3 (chart-vocabulary traceability survives UVM boundary):
  // every sos_seq_item carries chart_state / transition_id /
  // invariant_id — populated by the per-family sequence's body() task,
  // surfaced by the customer's scoreboard / monitor / assertion handler
  // in the chart-vocabulary failure-message format per §6.6.
  class sos_seq_item extends uvm_sequence_item;

    rand sos_event_family_e family;
    rand int                event_id;
    rand bit [63:0]         payload_data;
    rand string             chart_state;
    rand int                transition_id;
    rand int                invariant_id;

    `uvm_object_utils_begin(sos_seq_item)
      `uvm_field_enum(sos_event_family_e, family, UVM_ALL_ON)
      `uvm_field_int(event_id, UVM_ALL_ON)
      `uvm_field_int(payload_data, UVM_ALL_ON)
      `uvm_field_string(chart_state, UVM_ALL_ON)
      `uvm_field_int(transition_id, UVM_ALL_ON)
      `uvm_field_int(invariant_id, UVM_ALL_ON)
    `uvm_object_utils_end

    function new(string name = "sos_seq_item");
      super.new(name);
    endfunction

  endclass : sos_seq_item

  // -------------------------------------------------------------------------
  // sos_parse_chart_event_jsonl + sos_load_chart_event_jsonl —
  // SOS-08-F §6.4 wave-2 vector-IR JSONL parser
  // -------------------------------------------------------------------------
  //
  // Per the SOS-08-F §15 2026-05-24 wave-2 amendment, the chart's
  // bounded-reachability output is canonical JSONL per SOS-08
  // PCDN-009. Each line is one chart event; the row schema is:
  //
  //   {"event_id":<int>,"payload_data":<int>,"chart_state":"<str>",
  //    "transition_id":<int>,"invariant_id":<int>}
  //
  // No whitespace inside the JSON object. The chart_state value is
  // quoted; other values are bare decimal integers. Lines that don't
  // match are skipped with a UVM warning citing the offending text.
  //
  // The parser is package-level (NOT a sequence-class method) so any
  // per-family sequence's load_vector_ir() can invoke it without
  // duplicating the format-string contract.

  // Parse one JSONL line into an sos_chart_event_s. Returns 1 on
  // success, 0 on parse error (caller should skip the line).
  function automatic int sos_parse_chart_event_jsonl(
      input  string line,
      output sos_chart_event_s evt
  );
    int rc;
    int unsigned ev_id;
    longint unsigned payload;
    int unsigned tr_id;
    int unsigned inv_id;
    string chart_state_buf;
    rc = $sscanf(line,
      "{\"event_id\":%d,\"payload_data\":%d,\"chart_state\":\"%[^\"]\",\"transition_id\":%d,\"invariant_id\":%d}",
      ev_id, payload, chart_state_buf, tr_id, inv_id);
    if (rc != 5) begin
      return 0;
    end
    evt.event_id      = ev_id;
    evt.payload_data  = payload;
    evt.chart_state   = chart_state_buf;
    evt.transition_id = tr_id;
    evt.invariant_id  = inv_id;
    return 1;
  endfunction

  // Read a chart-vocabulary JSONL file from `path`, append each parsed
  // row to `events`. Empty / blank lines are skipped silently;
  // malformed lines emit a UVM warning and are skipped.
  //
  // The shared task is invoked by each per-family sequence's
  // `load_vector_ir` override. Customer-authored vector sources MAY
  // bypass the JSONL parser entirely by overriding `load_vector_ir`
  // at the sequence subclass level (per §6.5 customer-integration
  // contract).
  task automatic sos_load_chart_event_jsonl(
      input  string path,
      ref    sos_chart_event_s events[$]
  );
    int fh;
    string line;
    sos_chart_event_s evt;
    int parsed;
    int line_no;
    line_no = 0;
    fh = $fopen(path, "r");
    if (fh == 0) begin
      `uvm_warning("SOS-08-F",
        $sformatf("sos_load_chart_event_jsonl: cannot open '%s'", path))
      return;
    end
    while (!$feof(fh)) begin
      void'($fgets(line, fh));
      line_no++;
      // Skip empty / whitespace-only lines.
      if (line.len() < 2) continue;
      // Strip trailing newline if present ($fgets retains it).
      if (line.getc(line.len() - 1) == "\n")
        line = line.substr(0, line.len() - 2);
      if (line.len() == 0) continue;
      parsed = sos_parse_chart_event_jsonl(line, evt);
      if (parsed) begin
        events.push_back(evt);
      end else begin
        `uvm_warning("SOS-08-F",
          $sformatf("sos_load_chart_event_jsonl: skipping malformed line %0d: %s",
            line_no, line))
      end
    end
    $fclose(fh);
  endtask

  // -------------------------------------------------------------------------
  // sos_task_sequence — per-family stimulus sequence (family=task)
  // -------------------------------------------------------------------------
  //
  // Emits one sos_seq_item per chart event in the `task` family
  // (per SOS-08-F §6.1 + §6.3). The customer's sequencer accepts the
  // sos_seq_item; the customer's driver translates each item's
  // (family, event_id, payload_data) into DUT-pin-level activity per
  // §6.5 customer-integration contract.
  class sos_task_sequence extends uvm_sequence #(sos_seq_item);

    `uvm_object_utils(sos_task_sequence)

    // Vector IR path — set by customer test before start():
    //   seq.vector_path = "vectors/task_chart_bound.jsonl";
    string vector_path;

    function new(string name = "sos_task_sequence");
      super.new(name);
    endfunction

    // Customer override point per §5.6 + PCDN-SOS-08-F-005. Default:
    // no-op. Customer subclasses sos_task_sequence + overrides pre_body to inject
    // env quiescence waits / DUT preconditioning / scoreboard
    // snapshot logic.
    virtual task pre_body();
    endtask

    virtual task body();
      sos_chart_event_s events[$];
      sos_seq_item tx;
      int i;
      // Wave-1: load_vector_ir is a stub the customer's env wires to
      // its chart vector source. Wave-2 ships the full SOS-03 JSONL
      // parser (co-deferred with SOS-08-E's full vector-schema
      // consumer per the SOS-08-F §15 wave-1 entry).
      load_vector_ir(vector_path, events);
      foreach (events[i]) begin
        tx = sos_seq_item::type_id::create($sformatf("tx_%0d", i));
        start_item(tx);
        tx.family        = SOS_FAMILY_TASK;
        tx.event_id      = events[i].event_id;
        tx.payload_data  = events[i].payload_data;
        tx.chart_state   = events[i].chart_state;
        tx.transition_id = events[i].transition_id;
        tx.invariant_id  = events[i].invariant_id;
        finish_item(tx);
      end
    endtask

    // Customer override point per §5.6 + PCDN-SOS-08-F-005. Default:
    // no-op. Customer subclasses sos_task_sequence + overrides post_body to drain
    // scoreboard expectations / cycle quiescence / DUT teardown.
    virtual task post_body();
    endtask

    // Wave-2 (2026-05-24 §15) — JSONL vector-IR parser landed.
    // Calls the package-level shared sos_load_chart_event_jsonl task
    // which implements the strict JSONL row schema defined in
    // SOS-08-F §6.4. Customer MAY override this task at the sequence
    // subclass level to drive sequences from a non-JSONL source
    // (in-memory test-author-provided event list, alternative chart
    // export, regression harness feed) — per §6.5 customer-
    // integration contract.
    virtual task load_vector_ir(string path, ref sos_chart_event_s events[$]);
      events.delete();
      sos_load_chart_event_jsonl(path, events);
    endtask

  endclass : sos_task_sequence

  // -------------------------------------------------------------------------
  // sos_sem_sequence — per-family stimulus sequence (family=sem)
  // -------------------------------------------------------------------------
  //
  // Emits one sos_seq_item per chart event in the `sem` family
  // (per SOS-08-F §6.1 + §6.3). The customer's sequencer accepts the
  // sos_seq_item; the customer's driver translates each item's
  // (family, event_id, payload_data) into DUT-pin-level activity per
  // §6.5 customer-integration contract.
  class sos_sem_sequence extends uvm_sequence #(sos_seq_item);

    `uvm_object_utils(sos_sem_sequence)

    // Vector IR path — set by customer test before start():
    //   seq.vector_path = "vectors/sem_chart_bound.jsonl";
    string vector_path;

    function new(string name = "sos_sem_sequence");
      super.new(name);
    endfunction

    // Customer override point per §5.6 + PCDN-SOS-08-F-005. Default:
    // no-op. Customer subclasses sos_sem_sequence + overrides pre_body to inject
    // env quiescence waits / DUT preconditioning / scoreboard
    // snapshot logic.
    virtual task pre_body();
    endtask

    virtual task body();
      sos_chart_event_s events[$];
      sos_seq_item tx;
      int i;
      // Wave-1: load_vector_ir is a stub the customer's env wires to
      // its chart vector source. Wave-2 ships the full SOS-03 JSONL
      // parser (co-deferred with SOS-08-E's full vector-schema
      // consumer per the SOS-08-F §15 wave-1 entry).
      load_vector_ir(vector_path, events);
      foreach (events[i]) begin
        tx = sos_seq_item::type_id::create($sformatf("tx_%0d", i));
        start_item(tx);
        tx.family        = SOS_FAMILY_SEM;
        tx.event_id      = events[i].event_id;
        tx.payload_data  = events[i].payload_data;
        tx.chart_state   = events[i].chart_state;
        tx.transition_id = events[i].transition_id;
        tx.invariant_id  = events[i].invariant_id;
        finish_item(tx);
      end
    endtask

    // Customer override point per §5.6 + PCDN-SOS-08-F-005. Default:
    // no-op. Customer subclasses sos_sem_sequence + overrides post_body to drain
    // scoreboard expectations / cycle quiescence / DUT teardown.
    virtual task post_body();
    endtask

    // Wave-2 (2026-05-24 §15) — JSONL vector-IR parser landed.
    // Calls the package-level shared sos_load_chart_event_jsonl task
    // which implements the strict JSONL row schema defined in
    // SOS-08-F §6.4. Customer MAY override this task at the sequence
    // subclass level to drive sequences from a non-JSONL source
    // (in-memory test-author-provided event list, alternative chart
    // export, regression harness feed) — per §6.5 customer-
    // integration contract.
    virtual task load_vector_ir(string path, ref sos_chart_event_s events[$]);
      events.delete();
      sos_load_chart_event_jsonl(path, events);
    endtask

  endclass : sos_sem_sequence

  // -------------------------------------------------------------------------
  // sos_queue_sequence — per-family stimulus sequence (family=queue)
  // -------------------------------------------------------------------------
  //
  // Emits one sos_seq_item per chart event in the `queue` family
  // (per SOS-08-F §6.1 + §6.3). The customer's sequencer accepts the
  // sos_seq_item; the customer's driver translates each item's
  // (family, event_id, payload_data) into DUT-pin-level activity per
  // §6.5 customer-integration contract.
  class sos_queue_sequence extends uvm_sequence #(sos_seq_item);

    `uvm_object_utils(sos_queue_sequence)

    // Vector IR path — set by customer test before start():
    //   seq.vector_path = "vectors/queue_chart_bound.jsonl";
    string vector_path;

    function new(string name = "sos_queue_sequence");
      super.new(name);
    endfunction

    // Customer override point per §5.6 + PCDN-SOS-08-F-005. Default:
    // no-op. Customer subclasses sos_queue_sequence + overrides pre_body to inject
    // env quiescence waits / DUT preconditioning / scoreboard
    // snapshot logic.
    virtual task pre_body();
    endtask

    virtual task body();
      sos_chart_event_s events[$];
      sos_seq_item tx;
      int i;
      // Wave-1: load_vector_ir is a stub the customer's env wires to
      // its chart vector source. Wave-2 ships the full SOS-03 JSONL
      // parser (co-deferred with SOS-08-E's full vector-schema
      // consumer per the SOS-08-F §15 wave-1 entry).
      load_vector_ir(vector_path, events);
      foreach (events[i]) begin
        tx = sos_seq_item::type_id::create($sformatf("tx_%0d", i));
        start_item(tx);
        tx.family        = SOS_FAMILY_QUEUE;
        tx.event_id      = events[i].event_id;
        tx.payload_data  = events[i].payload_data;
        tx.chart_state   = events[i].chart_state;
        tx.transition_id = events[i].transition_id;
        tx.invariant_id  = events[i].invariant_id;
        finish_item(tx);
      end
    endtask

    // Customer override point per §5.6 + PCDN-SOS-08-F-005. Default:
    // no-op. Customer subclasses sos_queue_sequence + overrides post_body to drain
    // scoreboard expectations / cycle quiescence / DUT teardown.
    virtual task post_body();
    endtask

    // Wave-2 (2026-05-24 §15) — JSONL vector-IR parser landed.
    // Calls the package-level shared sos_load_chart_event_jsonl task
    // which implements the strict JSONL row schema defined in
    // SOS-08-F §6.4. Customer MAY override this task at the sequence
    // subclass level to drive sequences from a non-JSONL source
    // (in-memory test-author-provided event list, alternative chart
    // export, regression harness feed) — per §6.5 customer-
    // integration contract.
    virtual task load_vector_ir(string path, ref sos_chart_event_s events[$]);
      events.delete();
      sos_load_chart_event_jsonl(path, events);
    endtask

  endclass : sos_queue_sequence

  // -------------------------------------------------------------------------
  // sos_timer_sequence — per-family stimulus sequence (family=timer)
  // -------------------------------------------------------------------------
  //
  // Emits one sos_seq_item per chart event in the `timer` family
  // (per SOS-08-F §6.1 + §6.3). The customer's sequencer accepts the
  // sos_seq_item; the customer's driver translates each item's
  // (family, event_id, payload_data) into DUT-pin-level activity per
  // §6.5 customer-integration contract.
  class sos_timer_sequence extends uvm_sequence #(sos_seq_item);

    `uvm_object_utils(sos_timer_sequence)

    // Vector IR path — set by customer test before start():
    //   seq.vector_path = "vectors/timer_chart_bound.jsonl";
    string vector_path;

    function new(string name = "sos_timer_sequence");
      super.new(name);
    endfunction

    // Customer override point per §5.6 + PCDN-SOS-08-F-005. Default:
    // no-op. Customer subclasses sos_timer_sequence + overrides pre_body to inject
    // env quiescence waits / DUT preconditioning / scoreboard
    // snapshot logic.
    virtual task pre_body();
    endtask

    virtual task body();
      sos_chart_event_s events[$];
      sos_seq_item tx;
      int i;
      // Wave-1: load_vector_ir is a stub the customer's env wires to
      // its chart vector source. Wave-2 ships the full SOS-03 JSONL
      // parser (co-deferred with SOS-08-E's full vector-schema
      // consumer per the SOS-08-F §15 wave-1 entry).
      load_vector_ir(vector_path, events);
      foreach (events[i]) begin
        tx = sos_seq_item::type_id::create($sformatf("tx_%0d", i));
        start_item(tx);
        tx.family        = SOS_FAMILY_TIMER;
        tx.event_id      = events[i].event_id;
        tx.payload_data  = events[i].payload_data;
        tx.chart_state   = events[i].chart_state;
        tx.transition_id = events[i].transition_id;
        tx.invariant_id  = events[i].invariant_id;
        finish_item(tx);
      end
    endtask

    // Customer override point per §5.6 + PCDN-SOS-08-F-005. Default:
    // no-op. Customer subclasses sos_timer_sequence + overrides post_body to drain
    // scoreboard expectations / cycle quiescence / DUT teardown.
    virtual task post_body();
    endtask

    // Wave-2 (2026-05-24 §15) — JSONL vector-IR parser landed.
    // Calls the package-level shared sos_load_chart_event_jsonl task
    // which implements the strict JSONL row schema defined in
    // SOS-08-F §6.4. Customer MAY override this task at the sequence
    // subclass level to drive sequences from a non-JSONL source
    // (in-memory test-author-provided event list, alternative chart
    // export, regression harness feed) — per §6.5 customer-
    // integration contract.
    virtual task load_vector_ir(string path, ref sos_chart_event_s events[$]);
      events.delete();
      sos_load_chart_event_jsonl(path, events);
    endtask

  endclass : sos_timer_sequence

  // -------------------------------------------------------------------------
  // sos_event_sequence — per-family stimulus sequence (family=event)
  // -------------------------------------------------------------------------
  //
  // Emits one sos_seq_item per chart event in the `event` family
  // (per SOS-08-F §6.1 + §6.3). The customer's sequencer accepts the
  // sos_seq_item; the customer's driver translates each item's
  // (family, event_id, payload_data) into DUT-pin-level activity per
  // §6.5 customer-integration contract.
  class sos_event_sequence extends uvm_sequence #(sos_seq_item);

    `uvm_object_utils(sos_event_sequence)

    // Vector IR path — set by customer test before start():
    //   seq.vector_path = "vectors/event_chart_bound.jsonl";
    string vector_path;

    function new(string name = "sos_event_sequence");
      super.new(name);
    endfunction

    // Customer override point per §5.6 + PCDN-SOS-08-F-005. Default:
    // no-op. Customer subclasses sos_event_sequence + overrides pre_body to inject
    // env quiescence waits / DUT preconditioning / scoreboard
    // snapshot logic.
    virtual task pre_body();
    endtask

    virtual task body();
      sos_chart_event_s events[$];
      sos_seq_item tx;
      int i;
      // Wave-1: load_vector_ir is a stub the customer's env wires to
      // its chart vector source. Wave-2 ships the full SOS-03 JSONL
      // parser (co-deferred with SOS-08-E's full vector-schema
      // consumer per the SOS-08-F §15 wave-1 entry).
      load_vector_ir(vector_path, events);
      foreach (events[i]) begin
        tx = sos_seq_item::type_id::create($sformatf("tx_%0d", i));
        start_item(tx);
        tx.family        = SOS_FAMILY_EVENT;
        tx.event_id      = events[i].event_id;
        tx.payload_data  = events[i].payload_data;
        tx.chart_state   = events[i].chart_state;
        tx.transition_id = events[i].transition_id;
        tx.invariant_id  = events[i].invariant_id;
        finish_item(tx);
      end
    endtask

    // Customer override point per §5.6 + PCDN-SOS-08-F-005. Default:
    // no-op. Customer subclasses sos_event_sequence + overrides post_body to drain
    // scoreboard expectations / cycle quiescence / DUT teardown.
    virtual task post_body();
    endtask

    // Wave-2 (2026-05-24 §15) — JSONL vector-IR parser landed.
    // Calls the package-level shared sos_load_chart_event_jsonl task
    // which implements the strict JSONL row schema defined in
    // SOS-08-F §6.4. Customer MAY override this task at the sequence
    // subclass level to drive sequences from a non-JSONL source
    // (in-memory test-author-provided event list, alternative chart
    // export, regression harness feed) — per §6.5 customer-
    // integration contract.
    virtual task load_vector_ir(string path, ref sos_chart_event_s events[$]);
      events.delete();
      sos_load_chart_event_jsonl(path, events);
    endtask

  endclass : sos_event_sequence

  // -------------------------------------------------------------------------
  // sos_tick_sequence — per-family stimulus sequence (family=tick)
  // -------------------------------------------------------------------------
  //
  // Emits one sos_seq_item per chart event in the `tick` family
  // (per SOS-08-F §6.1 + §6.3). The customer's sequencer accepts the
  // sos_seq_item; the customer's driver translates each item's
  // (family, event_id, payload_data) into DUT-pin-level activity per
  // §6.5 customer-integration contract.
  class sos_tick_sequence extends uvm_sequence #(sos_seq_item);

    `uvm_object_utils(sos_tick_sequence)

    // Vector IR path — set by customer test before start():
    //   seq.vector_path = "vectors/tick_chart_bound.jsonl";
    string vector_path;

    function new(string name = "sos_tick_sequence");
      super.new(name);
    endfunction

    // Customer override point per §5.6 + PCDN-SOS-08-F-005. Default:
    // no-op. Customer subclasses sos_tick_sequence + overrides pre_body to inject
    // env quiescence waits / DUT preconditioning / scoreboard
    // snapshot logic.
    virtual task pre_body();
    endtask

    virtual task body();
      sos_chart_event_s events[$];
      sos_seq_item tx;
      int i;
      // Wave-1: load_vector_ir is a stub the customer's env wires to
      // its chart vector source. Wave-2 ships the full SOS-03 JSONL
      // parser (co-deferred with SOS-08-E's full vector-schema
      // consumer per the SOS-08-F §15 wave-1 entry).
      load_vector_ir(vector_path, events);
      foreach (events[i]) begin
        tx = sos_seq_item::type_id::create($sformatf("tx_%0d", i));
        start_item(tx);
        tx.family        = SOS_FAMILY_TICK;
        tx.event_id      = events[i].event_id;
        tx.payload_data  = events[i].payload_data;
        tx.chart_state   = events[i].chart_state;
        tx.transition_id = events[i].transition_id;
        tx.invariant_id  = events[i].invariant_id;
        finish_item(tx);
      end
    endtask

    // Customer override point per §5.6 + PCDN-SOS-08-F-005. Default:
    // no-op. Customer subclasses sos_tick_sequence + overrides post_body to drain
    // scoreboard expectations / cycle quiescence / DUT teardown.
    virtual task post_body();
    endtask

    // Wave-2 (2026-05-24 §15) — JSONL vector-IR parser landed.
    // Calls the package-level shared sos_load_chart_event_jsonl task
    // which implements the strict JSONL row schema defined in
    // SOS-08-F §6.4. Customer MAY override this task at the sequence
    // subclass level to drive sequences from a non-JSONL source
    // (in-memory test-author-provided event list, alternative chart
    // export, regression harness feed) — per §6.5 customer-
    // integration contract.
    virtual task load_vector_ir(string path, ref sos_chart_event_s events[$]);
      events.delete();
      sos_load_chart_event_jsonl(path, events);
    endtask

  endclass : sos_tick_sequence

endpackage : sos_uvm_seq_pkg
